# Generated by Django 2.1 on 2019-06-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='center_id',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='program_id',
            new_name='program',
        ),
    ]
