# Generated by Django 2.1 on 2019-06-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20190601_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centercategory',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
