# Generated by Django 2.1 on 2019-06-02 00:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_center_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='center/center/%Y/%M/%D'),
        ),
    ]
